### ISSUE TITLE
when load sam_model_best_large_ssl_kvasir.pth there is bug displays 

### ISSUE THREAD

**Issue by hagersalehahmed** [duyhominhnguyen/LVM-Med#10]
import torch
from segment_anything import sam_model_registry

DEVICE = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
MODEL_TYPE = "vit_b"

sam = sam_model_registry[MODEL_TYPE](checkpoint='sam_model_best_large_ssl_kvasir.pth')
sam.to(device=DEVICE)

RuntimeError: Attempting to deserialize object on CUDA device 3 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Comment by ngctnnnn** [comment]
Hi, 

Thanks for your response. I have checked through our code.

It turned out we forgot to map the SAM model into the suitable device. On training and saving our models, we use "cuda:3" instead of "cuda:0" and that is where the problem happened.

Now your code should operate normally. Once again, thanks for your notice.

**Comment by hagersalehahmed** [comment]
Are you update all our models to work on CUDA:0
https://drive.google.com/drive/u/0/folders/1tjrkyEozE-98HAGEtyHboCT2YHBSW15U

**Comment by ngctnnnn** [comment]
i updated the code to load model, rather than updated the pretrained weights.

**Comment by hagersalehahmed** [comment]
you updated this code
https://github.com/duyhominhnguyen/LVM-Med/blob/main/notebook/Prompt_Demo.ipynb

**Comment by ngctnnnn** [comment]
No. I updated directly in the [`sam_model_registry`](https://github.com/duyhominhnguyen/LVM-Med/blob/main/segment_anything/build_sam.py). You could view my latest commit for further details.

**Comment by hagersalehahmed** [comment]
Thank you the problem is solved
