### ISSUE TITLE
Classification tasks with ViT

### ISSUE THREAD

**Issue by sahil02235** [duyhominhnguyen/LVM-Med#12]
Hi @duyhominhnguyen 
Thanks for the great work. 
Can you please provide the fine-tuning code for classification tasks with ViT model. 

Thanks and regards,
Sahil

**Comment by duyhominhnguyen** [comment]
Hi @sahil02235 do you mean code to fine-tuning with VIT on classification with **our models**?

**Comment by sahil02235** [comment]
Yes, exactly. 
I have also requested for pre-training code. 
Can you please check.

**Comment by nghiemkythu** [comment]
Hi @sahil02235, I have uploaded the version of classification using VIT and files .yml to run VIT for FGADR dataset. The code use VIT for classification is in the folder "classification_VIT". 

If you want to run this version, you can run the same as the R50 version except that you change the key word "R50" to "VIT"
