### ISSUE TITLE
There is a problem with the download address of Resnet50 checkpoint

### ISSUE THREAD

**Issue by sleepontheafternoon** [duyhominhnguyen/LVM-Med#16]
Thanks for your great job! However, I have encountered a problem with the download address of the ResNet50 checkpoint. When I access it, Google Drive tells me that it doesn't exist.

**Comment by hoangNguyen210** [comment]
Hi @sleepontheafternoon, thank you a lot for your feedback. I have fixed the Resnet's [link](https://drive.google.com/file/d/16HCXhNdLaOm34jZiDkBeVloI9mP5ngBo/view?usp=sharing). Could you please recheck it? Thank you.

**Comment by sleepontheafternoon** [comment]
Thank you for your correction, and now the checkpoint address is correct.
