### ISSUE TITLE
Pretraining Code

### ISSUE THREAD

**Issue by ChandayHunt** [duyhominhnguyen/LVM-Med#2]
Dear author,
Thank you for your impressive work! Could you please also share the pretraining code regarding the method in your paper? Thank you!

**Comment by ChandayHunt** [comment]
Cool, thank you!

**Comment by Marrywithyou** [comment]
Dear author，
May I ask whether the pre-trained algorithm has been published? Besides, there seems to be a problem with the weight of resnet50 provided, which is not a normal file

**Comment by duyhominhnguyen** [comment]
Hi @Marrywithyou and @ChandayHunt, I will prepare some forms and will ask you to provide some basic information about the purpose of using the codes. Based on this, we will send you a link to download it.

**Comment by duyhominhnguyen** [comment]
@Marrywithyou can you specify your problem with ResNet-50?

**Comment by Marrywithyou** [comment]
@duyhominhnguyen  
Hello, I am a graduate student from Shenzhen University, and my direction is also related to self-supervised learning. I have seen the excellent effect of your method on downstream tasks, and I would like to see if I can optimize the work on the basis of your algorithm. Thank you very much for providing me with some basic information about the purpose of using the codes
In addition, there is no problem with the resnet50 model you provided, but I made a mistake before

**Comment by Marrywithyou** [comment]
Dear author，
I would like to ask if you can help provide the download link of the data set for self-supervised training in the article. I have been worried about the large number of data sets required for self-supervised learning。It doesn't matter if it is inconvenient. Thank you very much for your reply

**Comment by duyhominhnguyen** [comment]
Hi @Marrywithyou, unfortunately, due to data privacy, we cannot provide the link to download datasets. As mentioned in the paper, most of them require you to sign the form to download, and we cannot only re-distribute data given signed requirements.

**Comment by Marrywithyou** [comment]
@duyhominhnguyen Yeah, well understood, would you like to provide the algorithm code used in pre-training.My purpose is to use it for my master's graduation subject.

**Comment by duyhominhnguyen** [comment]
@ChandayHunt please send me an email regarding LVM-Med pre-training code. Thank you.
