### ISSUE TITLE
Can you support computation on 3D DICE/IOU scores?

### ISSUE THREAD

**Issue by GewelsJI** [duyhominhnguyen/LVM-Med#3]

**Comment by duyhominhnguyen** [comment]
Hi @GewelsJI, yes, we already involve result estimation with 3D IOU scores in 3D segmentation downstream tasks. 

You can run an example by ```python train_segmentation.py -c ./dataloader/yaml_data/mmwhs_ct_endtoend_R50.yml``` (MMWHS-CT dataset) or ```python train_segmentation.py -c ./dataloader/yaml_data/mmwhs_mr_endtoend_R50.yml``` (MMWHS-MRI dataset).

These scripts will call the function ```evaluate_3d_iou``` in  [evaluate.py](https://github.com/duyhominhnguyen/LVM-Med/blob/main/evaluate.py). Hope it help!

**Comment by GewelsJI** [comment]
Thanks. But it does not support calculation of 3D dice score, could you provide some available reimplementations?

**Comment by duyhominhnguyen** [comment]
@GewelsJI Oke, we have updated the ```evaluate_3d_dice``` in [evaluate.py](https://github.com/duyhominhnguyen/LVM-Med/blob/main/evaluate.py) for 3D Dice. You can check it now!

**Comment by GewelsJI** [comment]
Big thanks. Another question is how to download ~1.3 million medical images that you mentioned?

**Comment by duyhominhnguyen** [comment]
We summarize all used datases in the Table 13, Section F in the Appendix of [LVM-Med's paper](https://arxiv.org/pdf/2306.11925.pdf). You have to access each link and download one-by-one by yourself. Due to data privacy, we cannot host the dataset.

**Comment by GewelsJI** [comment]
That's good. BTW, strongly recommend you a largest colonoscopy video dataset for polyp segmentation: https://github.com/GewelsJI/VPS/tree/main

**Comment by duyhominhnguyen** [comment]
Great suggestions! We would consider training another version of LVM-Med (SSL) including your dataset.
