### ISSUE TITLE
add open dataset of livecell https://sartorius-research.github.io/LIVECell/

### ISSUE THREAD

**Issue by aiyou9** [duyhominhnguyen/LVM-Med#5]
https://github.com/sartorius-research/LIVECell

https://github.com/sartorius-research/LIVECell/blob/main/model/README.md

**Comment by duyhominhnguyen** [comment]
Hi @aiyou9, can you please clarify precisely your question?

**Comment by aiyou9** [comment]
> Hi @aiyou9, can you please clarify precisely your question?

Add LIVECell image DataSet as demo dataset in LVM-Med, and it maybe  great that you may  train for Resnet-50 or VIT pre-trained models, just  a advise

**Comment by duyhominhnguyen** [comment]
Thanks, your suggestion is similar to the current [one](https://github.com/duyhominhnguyen/LVM-Med/issues/4). We will release another version of LVM-Med with both ResNet-50 and ViT using current pre-trained weights and further pre-trained them on LIVECell dataset.

**Comment by aiyou9** [comment]
> [谢谢，您的建议与目前的](https://github.com/duyhominhnguyen/LVM-Med/issues/4)类似。我们将发布另一个版本的 LVM-Med，其中包含 ResNet-50 和 ViT，使用当前的预训练权重，并在 LIVECell 数据集上进一步对其进行预训练。

great！

**Comment by duyhominhnguyen** [comment]
Hi @aiyou9, we have released the model (ViT) trained on the LIVE-CELL dataset. If you are interested, please check this [section](https://github.com/duyhominhnguyen/LVM-Med/tree/main#further-training-lvm-med-on-large-dataset).

**Comment by aiyou9** [comment]
nice work! I will use it and give a citation of your work in my paper

**Comment by duyhominhnguyen** [comment]
@aiyou9 ViT-H with 632M params on LIVE-CELL is available now!
