### ISSUE TITLE
Using the resnet-50 model

### ISSUE THREAD

**Issue by gowtham07** [duyhominhnguyen/LVM-Med#6]
Hello,
 
Thank you so much for the pre-trained models on Medical dataset. I would like to use the resnet-50, vit models to finetune on a  downstream task like [Brain Tumor Classification (MRI)] etc . My aim is to generate sailency features from different models to see if they kind of learn same thing. For this it is important that the model did not see in pre-training. I would like to know if model was pretrained on these dataset (Kvasir, BUID, FGADR, MMWHS_MR_Heart and MMWHS_CT_Heart, brain tumor classification) . 

Thanks!!

**Comment by duyhominhnguyen** [comment]
Hi @gowtham07, sorry for the late response.

You can check the Table in the Appendix where we summarized all of dataset used in the pre-training stage. Generally, there are a few datasets seen in the pre-training stage, like MMWHS_MR, MMWHS-CT, etc; however, we excluded samples used in a pre-training stage in the fine-tuning step; therefore, data leaking should not occur! Let me know if you have further questions. Thank you.
