### ISSUE TITLE
support onnx deployment 

### ISSUE THREAD

**Issue by aiyou9** [duyhominhnguyen/LVM-Med#7]
[segment-anything#onnx-export](https://github.com/facebookresearch/segment-anything#onnx-export) in facebook project and another work
[samexporter](https://github.com/vietanhdev/samexporter)  is a project to transfer SAM to ONNX, It may has some help

**Comment by ngctnnnn** [comment]
Thanks, we will consider onnx as a part in our upcoming development

**Comment by aiyou9** [comment]
> Thanks, we will consider onnx as a part in our upcoming development

great, I hope your work can be used in [anylabeling](https://github.com/vietanhdev/anylabeling) or [x-anylabeling](https://github.com/CVHub520/X-AnyLabeling), that is great!

**Comment by ngctnnnn** [comment]
Hi @aiyou9, I have just uploaded the onnx support in folder `onnx_model`. Hope it could help you with your future work.

**Comment by aiyou9** [comment]
> Hi @aiyou9, I have just uploaded the onnx support in folder `onnx_model`. Hope it could help you with your future work.

I want use the vit model of livecell in your project， please make an onnx output of pre-model of livecell，
 or 
Can I use  your transfer py script to do it by myself？
